---
caching:
  expires: 3600
db:
  fb:
    adapter: mysql2
    encoding: utf8
    host: HOST_HERE
    username: USERNAME_HERE
    password: PASSWORD_HERE
    port: 3306
    database: fbapp
  slb:
    adapter: mysql2
    encoding: utf8
    host: HOST_HERE
    username: USERNAME_HERE
    password: PASSWORD_HERE
    port: 3306
    database: slbapp
